version: '3.8'  

 services:   
  web:    
  build: .     
  ports:       
    - "80:5000"     
  volumes:      
    - sqlite_data:/data     
  environment:       
    - FLASK_ENV=production     
   restart: unless-stopped  
   volumes:   sqlite_data:
